import { Material } from '../types/Material';

// eslint-disable-next-line no-unused-vars
const shops = [
  'https://runescape.wiki/w/Tamayu%27s_Spear_Stall',
  'https://runescape.wiki/w/Aleck%27s_Hunter_Emporium',
  'https://runescape.wiki/w/White_Knight_Master_Armoury',
];

const relics = 'ED1-4 relics';

export const commonMaterials:Material[] = [
  {
    icon: 'https://runescape.wiki/images/Base_parts.png?6c137',
    name: 'Base parts',
    level: 1,
    sources: 'Bolts, weapons with hilts, shields',
    items: ['Bolts', 'Scimitars', 'Swords', 'Longswords', '2h Swords', 'Dragonhide/Leather Shield', 'Hand cannon shot', 'Bladed salvages'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Base',
  },
  {
    icon: 'https://runescape.wiki/images/Blade_parts.png?87851',
    name: 'Blade parts',
    level: 1,
    sources: 'Stabbing, slashing and thrown weapons',
    items: ['Darts', 'Bladed salvages', 'Javelins', 'Scimitars', 'Swords', 'Longswords', '2h Swords', 'Claws', 'Spears', 'Whips'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Blade',
  },
  {
    icon: 'https://runescape.wiki/images/Clear_parts.png?4e728',
    name: 'Clear parts',
    level: 1,
    sources: 'Gems, glass',
    items: ['Gems', relics, 'Empty light orb'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Clear',
  },
  {
    icon: 'https://runescape.wiki/images/Connector_parts.png?011ea',
    name: 'Connector parts',
    level: 1,
    sources: 'Claws, whips, crossbows, hatchets, jewellery',
    items: ['Whips', 'Claws', 'Black salamander', 'Ring of slaying', 'Spiky salvages', 'Jewellery', 'Crossbows', relics, 'Unstrung symbol'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Connector',
  },
  {
    icon: 'https://runescape.wiki/images/Cover_parts.png?e0cbe',
    name: 'Cover parts',
    level: 1,
    sources: 'Armour, shields, clothing',
    items: ['Spiked gauntlets', 'Plated salvages', 'Spider silk robe bottom', 'Dragonhide armour', 'Armour', 'Team capes', 'Nose peg'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Cover',
  },
  {
    icon: 'https://runescape.wiki/images/Crafted_parts.png?27cd3',
    name: 'Crafted parts',
    level: 1,
    sources: 'Summoning scrolls and pouches, spears, arrows, two-handed crossbows, potions, bars, planks, leather',
    items: ['Summoning pouches', 'Runes', 'Potions', 'Antipoison', 'Black salamander', 'Broad arrows', 'ED4 relics', 'talismans', 'Spiky salvages', 'Gnome food', 'Raw food'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Crafted',
  },
  {
    icon: 'https://runescape.wiki/images/Crystal_parts.png?5a066',
    name: 'Crystal parts',
    level: 1,
    sources: 'Harmonic dust, non-attuned crystal items, crystal tree blossoms',
    items: ['Augmented Crystal Hammer', 'Crystal teleport seed(4-8)', 'Augmented Crystal Halberd'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Crystal',
  },
  {
    icon: 'https://runescape.wiki/images/Deflecting_parts.png?ffc37',
    name: 'Deflecting parts',
    level: 1,
    sources: 'Hybrid/melee/magic armour, shields, defenders, halberds',
    items: ['Spiked gauntlets', 'Plated salvages', 'Insulated boots', 'Spider silk robe bottom', 'Team capes', 'Armour', 'Dragonhide shields'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Deflecting',
  },
  {
    icon: 'https://runescape.wiki/images/Delicate_parts.png?5c745',
    name: 'Delicate parts',
    level: 1,
    sources: 'Orbs and books, jewellery, potions, glass, gems',
    items: ['Potions', 'Cut gems', 'Jewellery', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Delicate',
  },
  {
    icon: 'https://runescape.wiki/images/Flexible_parts.png?f937a',
    name: 'Flexible parts',
    level: 1,
    sources: 'Whips, bows, Summoning pouches',
    items: ['Yew shieldbow', 'Magic shieldbow', 'Maple shortbow', 'Terrorbirds/Pouchs', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Flexible',
  },
  {
    icon: 'https://runescape.wiki/images/Head_parts.png?4fa64',
    name: 'Head parts',
    level: 1,
    sources: 'Hatchets, battleaxes, blunt weapons, pickaxes, wands, ammunition',
    items: ['Adamant bolts', 'Blunt salvages', 'Warhammers', 'Battleaxes', 'Maces', 'Broad bolts', 'Broad arrows', 'Hand cannon shot', 'Bolt rack', 'Bolas', 'Pickaxe', 'Axe', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Head',
  },
  {
    icon: 'https://runescape.wiki/images/Magic_parts.png?59b23',
    name: 'Magic parts',
    level: 1,
    sources: 'Runes, signs and portents, magic weapons, magic armour',
    items: ['Runes', 'Talismans', 'Spider silk robe bottom', 'Battlestaves', 'Mystic armour', 'Staves', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Magic',
  },
  {
    icon: 'https://runescape.wiki/images/Metallic_parts.png?0cea8',
    name: 'Metallic parts',
    level: 1,
    sources: 'Swords, knives',
    items: ['Bladed salvages', 'Swords', 'Throwing knives', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Metallic',
  },
  {
    icon: 'https://runescape.wiki/images/Organic_parts.png?ab56e',
    name: 'Organic parts',
    level: 1,
    sources: 'Seeds, bones, ashes, food, herbs, potions',
    items: ['Woad leaf', 'Cooked beltfish', 'Cooked food', 'Raw food', 'Gnome food', 'Pineapples', 'Potions', 'Snape grass', 'Watermelon', 'Seeds', 'Potato Cactus'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Organic',
  },
  {
    icon: 'https://runescape.wiki/images/Padded_parts.png?17a91',
    name: 'Padded parts',
    level: 1,
    sources: 'Ranged armour, clothing, staves',
    items: ['Ranged armour', 'Battlestaff', 'Battlestaves', 'Augmented sunspear magic', 'Nose peg', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Padded',
  },
  {
    icon: 'https://runescape.wiki/images/Plated_parts.png?d2c95',
    name: 'Plated parts',
    level: 1,
    sources: 'Mauls, thrown axes, melee armour',
    items: ['Plated salvages', 'Boots', 'Gauntlets', 'Armour', 'Throwing Axes', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Plated',
  },
  {
    icon: 'https://runescape.wiki/images/Simple_parts.png?106b0',
    name: 'Simple parts',
    level: 1,
    sources: 'Ores, logs, hides, bars, planks, leather, basic weapons and clothing',
    items: ['Acadia logs', 'Maple logs', 'Ore', 'Batwing', 'Dragonhide', 'Bolas'],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Simple',
  },
  {
    icon: 'https://runescape.wiki/images/Smooth_parts.png?a2966',
    name: 'Smooth parts',
    level: 1,
    sources: 'Glass, gems, jewellery, orbs and books, warhammers, maces, battleaxes',
    items: ['Cut gems', 'Blunt salvages', 'Maces', 'Battleaxes', ' Unstrung symbol', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Smooth',
  },
  {
    icon: 'https://runescape.wiki/images/Spiked_parts.png?d83b4',
    name: 'Spiked parts',
    level: 1,
    sources: 'Daggers, claws, one-handed crossbows, thrown weapons, bolts',
    items: ['Adamant Bolts', 'Claws', 'Darts', 'Bolt rack', 'Hand cannon shot', 'Spiky salvage', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Spiked',
  },
  {
    icon: 'https://runescape.wiki/images/Spiritual_parts.png?b349d',
    name: 'Spiritual parts',
    level: 1,
    sources: 'Summoning charms, scrolls and pouches',
    items: ['Abyssal Titan', 'Barker toad', 'Bunyp', 'Granite lobster', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Spiritual',
  },
  {
    icon: 'https://runescape.wiki/images/Stave_parts.png?7b103',
    name: 'Stave parts',
    level: 1,
    sources: 'Arrows, staves, spears, halberds, bows',
    items: ['Broad arrow', 'Battlestaff', 'Blunt salvages', 'Bows', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Stave',
  },
  {
    icon: 'https://runescape.wiki/images/Tensile_parts.png?9100a',
    name: 'Tensile parts',
    level: 1,
    sources: 'Bows, crossbows, ranged armour',
    items: ['Yew shieldbow', 'Magic shieldbow', 'Black salamander', 'Ranged armour', relics],
    info: 'https://runescape.wiki/w/Calculator:Disassembly_by_material/Tensile',
  },
];
